### ISSUE TITLE
junit path name in dyntrace.py

### ISSUE THREAD

**Issue by markro49** [SRI-CSL/do-like-javac#11]
It seems that os.path.exists(junit_after_path) doesn't like the ".." in the path; I was able to get it to work by adding normpath:

 junit_after_path = os.path.normpath(os.path.join(test_src_dir, "..", "junit-after"))

**Comment by tim-mccarthy** [comment]
Fixed with c2dfbceb26bdb842394067cdae7a3bc4482bdc46.
