### ISSUE TITLE
Feature request: provide individual test case access to dyntrace omit-list items

### ISSUE THREAD

**Issue by markro49** [SRI-CSL/do-like-javac#12]
While the dyntrace  omit-list and junit-after system works well, it is a bit of a large hammer.  For corpus tests like boofcv or jmonkeyengine with a large number of sub-tests it would be nice to be able to selective apply a different omit-list for each sub-test instead of across the board.

**Comment by tim-mccarthy** [comment]
What do you think would be the best way to specify which subtest an omit-list or junit-after file applies to? Would going number within the sequence of subtests work?

For example, if you had

    dyntrace/boofcv.omit-list
    dyntrace/boofcv.omit-list.2
    dyntrace/boofcv.omit-list.3

subtests 2 and 3 would get their own specific omit lists, and all other subtests would fall back to the default omit list.

**Comment by markro49** [comment]
That would be fine.  Also, having the default helps during transition to individual ones.

**Comment by tim-mccarthy** [comment]
This is now implemented, and the integration-test infrastructure has been tweaked to support it.
