### ISSUE TITLE
File tool.log isn't the tool's log; it is the tool's output

### ISSUE THREAD

**Issue by mernst** [SRI-CSL/do-like-javac#22]
[Line 59 in file `common.py`](https://github.com/SRI-CSL/do-like-javac/blob/master/do_like_javac/tools/common.py#L59) creates a file with a name like `randoop.log`.  This is a bit misleading, because the output is the captured standard output (maybe the standard error too?), rather than a log.  The tools may have separate logging mechanisms.

I would personally rename this to something like `randoop-output.txt` or `randoop-stdout.txt`.  This isn't a big deal either way, though.

**Comment by hsanchez** [comment]
closed by #29
